BankingWebApp/Models/ErrorViewModel.cs
namespace BankingWebApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

BankingWebApp/Controllers/BankController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BankingWebApp.Models;
using BLL;
using BOL;
namespace BankingWebApp.Controllers;

public class BankController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public BankController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }


    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Register()
    {
        Account account = new Account();
        return View(account);
    }


    [HttpPost]
    public IActionResult Register(Account regaccount)
    {
        if(!ModelState.IsValid){
        
        return View();
        }
      
        Console.WriteLine(regaccount.Account_Balance+" "+regaccount.Account_Branch+" "+regaccount.Customer_Name);
        
        return RedirectToAction("Login");
    
    }


    public IActionResult Login()
    {

        return View();
    }

    [HttpPost]
    public IActionResult Login(string email, string password)
    {
        Console.WriteLine("hello");
        // Console.WriteLine(email , password);
        if(email == "akash.gothria678@gmail.com" && password == "akash")
        {
             Console.WriteLine("hello");
           return RedirectToAction("welcome");
        }


        return View();
    }

    public IActionResult welcome()
    {
        BankManager mgr=new BankManager();
        List<Account> accts=mgr.GetAllAccountsMg();
        this.ViewData["accts"]=accts;
        return View();
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

BankingWebApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BankingWebApp.Models;

namespace BankingWebApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }
      public IActionResult Home()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

BankingWebApp/Views/Bank/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center, container">
    <h1 class="display-4">Welcome to My Bankadfdf</h1>
</div>

BankingWebApp/Views/Bank/Login.cshtml
<div>
    <div>
        <br>
        <h4>Login</h4>
    </div>
<form class="form-control" method="post" action="/Bank/Login">
  <div class="mb-3">
    <label for="email" class="form-label">Email address</label>
    <input type="email" class="form-control" id="email"  name="email" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="password" class="form-label">Password</label>
    <input type="password" class="form-control"  name="password" id="password">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

BankingWebApp/Views/Bank/Register.cshtml
@using BOL;

@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h1>Online Banking Application</h1>
</div>
<br>
<form asp-controller="Bank" asp-action="Register" method="post" class="form-control" style="margin:10px">
    <fieldset>
        <legend> <h4>Registration Form </h4></legend>
        <br>

        <div class="form-group">
        @model Account
            Select Account Type
            @Html.DropDownListFor(m => m.Type, 
            new SelectList(Enum.GetValues(typeof(Account_Type))), 
            "Select Any one")
             </div>
             <br>
        <div class="form-group">
            <label for="Account_Branch">Branch</label>
            <input id="Account_Branch" id="Account_Branch" class="form-control" asp-for="Account_Branch" />
        </div>
        <br>
        <div class="form-group">
            <label for="Account_Balance">Balance</label>
            <input id="Account_Balance" id="Account_Balance" class="form-control" asp-for="Account_Balance" />
        </div>
        <br>
        <div class="form-group">
            <label for="Customer_Name">Name</label>
            <input id="Customer_Name" id="Customer_Name" class="form-control" asp-for="Customer_Name" />
        </div>
        <br>
        <div class="form-group">
            <label for="Customer_Address">Address</label>
            <input id="Customer_Address" id="Customer_Address" class="form-control" asp-for="Customer_Address" />
        </div>
        <br>
        <div class="form-group">
            <label for="Customer_PAN">PAN</label>
            <input id="Customer_PAN" id="Customer_PAN" class="form-control" asp-for="Customer_PAN" />
        </div>
        <br>
        <div class="form-group">
            <label for="Customer_Mobile">Mobile</label>
            <input id="Customer_Mobile" id="Customer_Mobile" class="form-control" asp-for="Customer_Mobile" />
        </div>
        <br>
        <div class="form-group">
            <input type="submit" value="Submit" class="btn btn-primary" />
            <input type="submit" value="Back" class="btn btn-secondary" />
        </div>
    </fieldset>
</form>

BankingWebApp/Views/Bank/welcome.cshtml
@using BOL;

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center, container">
    <h1 class="display-4">Welcome to Customer Page</h1>

  @{
        List<Account> allaccounts= (List<Account>)ViewData["accts"];
            Console.WriteLine("in the second div of ");
        @if(allaccounts != null){
        <table class="table table-striped">
        <thead>
        <tr>
        <th>Customer Name</th>
         <th>Account Type</th>
          <th>Branch</th>
           <th>Balance</th>
        
        </tr>
        </thead>
        <tbody>
            @foreach( Account acc in allaccounts){
                Console.WriteLine();
                <tr>
            


                <td>@acc.Customer_Name</td>
                <td>@acc.Type</td>
                <td>@acc.Account_Branch</td> 
                <td>@acc.Account_Balance</td>
                 </tr>
                
                
            }    
            </tbody>
            </table>  
        }  
         Console.WriteLine("Data no found");
    }
    </div>

BankingWebApp/Views/Home/Home.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">HOME</h1>
</div>

BankingWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to My Bank</h1>
</div>

BankingWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BankingWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BankingWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3 justify-content-between ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">My Bank</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Bank" asp-action="Register">Sign up</a>
                         </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Bank" asp-action="Login">Login</a>
                        </li>
                         
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BankingWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>